//! Render-target adapters (design §3): the [`RenderTarget`] trait, the
//! [`Action`] plan model shared by render/diff/apply, and the hardcoded
//! never-touch denylist.

pub mod claude;
pub mod codex;
pub mod denylist;
pub mod grammar;

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::error::Error;
use crate::schema::merge::ResolvedProfile;
use crate::schema::types::Target;

/// Where target files live (design §2 `--scope`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, clap::ValueEnum)]
#[serde(rename_all = "lowercase")]
pub enum Scope {
    Repo,
    User,
}

/// One planned mutation — exact shapes from the design §3.4 state records,
/// minus hashes. Serializes to the `render --json` action contract (§2).
///
/// `path` is a *display path*: `~/`-prefixed for home-scoped files, otherwise
/// repo-relative. [`PlanContext::resolve`] turns it into an absolute path.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "op")]
pub enum Action {
    #[serde(rename = "create")]
    Create { path: String, content: String },
    /// Key-level surgical merge; `content` is the fragment (same format as
    /// the target file) holding only the keys we add.
    #[serde(rename = "merge-keys")]
    MergeKeys {
        path: String,
        keys: Vec<String>,
        content: String,
    },
    #[serde(rename = "symlink")]
    Symlink {
        path: String,
        #[serde(rename = "linkTarget")]
        link_target: String,
    },
    #[serde(rename = "append-block")]
    AppendBlock {
        path: String,
        marker: String,
        content: String,
    },
}

impl Action {
    pub fn path(&self) -> &str {
        match self {
            Action::Create { path, .. }
            | Action::MergeKeys { path, .. }
            | Action::Symlink { path, .. }
            | Action::AppendBlock { path, .. } => path,
        }
    }

    pub fn op(&self) -> &'static str {
        match self {
            Action::Create { .. } => "create",
            Action::MergeKeys { .. } => "merge-keys",
            Action::Symlink { .. } => "symlink",
            Action::AppendBlock { .. } => "append-block",
        }
    }
}

/// A profile field (or part of one) the target cannot express. Surfaced in
/// render output and consumed by doctor — never silently dropped (design §3.1).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Skipped {
    pub field: String,
    pub reason: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hint: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Plan {
    pub actions: Vec<Action>,
    pub skipped: Vec<Skipped>,
    /// Honest-limitation notes surfaced verbatim in render output
    /// (e.g. the project-wide settings caveat, design §3.2.3).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub notes: Vec<String>,
}

/// Everything an adapter needs to compute paths.
#[derive(Debug, Clone)]
pub struct PlanContext {
    pub scope: Scope,
    /// Repository root (the parent of `.agent-profile/`).
    pub repo_root: PathBuf,
    /// The `.agent-profile/` directory itself (fragments live under it).
    pub workspace_root: PathBuf,
    pub home: PathBuf,
    /// Set by `apply` (S4); render/diff plans fall back to a role-based
    /// marked-block marker.
    pub session_id: Option<String>,
}

impl PlanContext {
    /// Expand a display path: `~/…` resolves under home, anything else under
    /// the repo root.
    pub fn resolve(&self, display: &str) -> PathBuf {
        match display.strip_prefix("~/") {
            Some(rest) => self.home.join(rest),
            None => self.repo_root.join(display),
        }
    }
}

/// The adapter contract (design §7).
pub trait RenderTarget {
    fn target(&self) -> Target;
    fn plan(&self, resolved: &ResolvedProfile, ctx: &PlanContext) -> Result<Plan, Error>;
}

/// Adapter lookup.
pub fn adapter_for(target: Target) -> Option<Box<dyn RenderTarget>> {
    match target {
        Target::CodexAgent => Some(Box::new(codex::CodexAgent)),
        Target::ClaudeSubagent => Some(Box::new(claude::ClaudeSubagent)),
        Target::ClaudeTeammate => Some(Box::new(claude::ClaudeTeammate)),
    }
}

/// Provenance header for owned TOML files (design §3.0).
pub fn provenance_header_toml(role: &str) -> String {
    format!(
        "# generated by agent-profile v{} — role: {role} — do not hand-edit",
        env!("CARGO_PKG_VERSION")
    )
}

/// Provenance header for owned Markdown files (design §3.0).
pub fn provenance_header_md(role: &str) -> String {
    format!(
        "<!-- generated by agent-profile v{} — role: {role} — do not hand-edit -->",
        env!("CARGO_PKG_VERSION")
    )
}

/// Marked-block marker: `session=<id>` during apply, `role=<role>` for
/// render/diff (design §3.2.5).
pub fn block_marker(ctx: &PlanContext, role: &str) -> String {
    match &ctx.session_id {
        Some(id) => format!("session={id}"),
        None => format!("role={role}"),
    }
}

/// Marked `@include` stub block for CLAUDE.md/AGENTS.md (design §3.2.5/§3.3.3).
pub fn marked_block(marker: &str, role: &str, context: &[String]) -> String {
    // When the marker is already role-based, do not repeat the role attr.
    let role_attr = if marker.starts_with("role=") {
        String::new()
    } else {
        format!(" role={role}")
    };
    let mut block = format!("<!-- agent-profile:begin {marker}{role_attr} -->\n");
    for fragment in context {
        block.push_str(&format!("@.agent-profile/{fragment}\n"));
    }
    block.push_str(&format!("<!-- agent-profile:end {marker} -->\n"));
    block
}

/// What `path` should contain after `action` runs against `current`
/// (`None` = file does not exist). Used by `diff` now and `apply` in S4.
pub fn desired_file_state(action: &Action, current: Option<&str>) -> Result<String, Error> {
    match action {
        Action::Create { content, .. } => Ok(content.clone()),
        Action::MergeKeys {
            path,
            keys,
            content,
        } => {
            if Path::new(path).extension().is_some_and(|e| e == "toml") {
                codex::merge_toml_fragment(current.unwrap_or(""), content, path)
            } else {
                claude::merge_json_fragment(current.unwrap_or(""), content, keys, path)
            }
        }
        Action::AppendBlock {
            marker, content, ..
        } => {
            let cur = current.unwrap_or("");
            if cur.contains(&format!("<!-- agent-profile:begin {marker}")) {
                return Ok(cur.to_string());
            }
            let mut out = cur.to_string();
            if !out.is_empty() && !out.ends_with('\n') {
                out.push('\n');
            }
            out.push_str(content);
            Ok(out)
        }
        Action::Symlink { .. } => Err(Error::NotImplemented),
    }
}

/// Materialize a plan into a sandbox directory (`render --out`). `~/` display
/// paths land under the same tree with the prefix stripped; nothing outside
/// `out` is touched.
pub fn materialize(plan: &Plan, out: &Path) -> Result<Vec<PathBuf>, Error> {
    let mut written = Vec::new();
    for action in &plan.actions {
        let rel = action.path().strip_prefix("~/").unwrap_or(action.path());
        let dest = out.join(rel);
        match action {
            Action::Create { content, .. }
            | Action::MergeKeys { content, .. }
            | Action::AppendBlock { content, .. } => atomic_write(&dest, content)?,
            Action::Symlink { link_target, .. } => {
                ensure_parent(&dest)?;
                #[cfg(unix)]
                std::os::unix::fs::symlink(link_target, &dest).map_err(|source| Error::Io {
                    path: dest.clone(),
                    source,
                })?;
                #[cfg(not(unix))]
                return Err(Error::NotImplemented);
            }
        }
        written.push(dest);
    }
    Ok(written)
}

/// Atomic write-then-rename (design §7) — used for every file mutation.
pub fn atomic_write(dest: &Path, content: &str) -> Result<(), Error> {
    let dir = ensure_parent(dest)?;
    let io_err = |source| Error::Io {
        path: dest.to_path_buf(),
        source,
    };
    let mut tmp = tempfile::NamedTempFile::new_in(dir).map_err(io_err)?;
    std::io::Write::write_all(&mut tmp, content.as_bytes()).map_err(io_err)?;
    tmp.persist(dest).map_err(|e| io_err(e.error))?;
    Ok(())
}

fn ensure_parent(dest: &Path) -> Result<&Path, Error> {
    let dir = dest.parent().unwrap_or(Path::new("."));
    std::fs::create_dir_all(dir).map_err(|source| Error::Io {
        path: dir.to_path_buf(),
        source,
    })?;
    Ok(dir)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// S2-T1: a synthetic adapter's plan round-trips through the §2 JSON
    /// action contract.
    struct Synthetic;

    impl RenderTarget for Synthetic {
        fn target(&self) -> Target {
            Target::CodexAgent
        }
        fn plan(&self, _resolved: &ResolvedProfile, _ctx: &PlanContext) -> Result<Plan, Error> {
            Ok(synthetic_plan())
        }
    }

    fn synthetic_plan() -> Plan {
        Plan {
            actions: vec![
                Action::Create {
                    path: ".codex/agents/reviewer.toml".into(),
                    content: "name = \"reviewer\"\n".into(),
                },
                Action::MergeKeys {
                    path: "~/.codex/config.toml".into(),
                    keys: vec!["mcp_servers.github".into()],
                    content: "[mcp_servers.github]\ncommand = \"github-mcp\"\n".into(),
                },
                Action::Symlink {
                    path: ".claude/skills/code-review".into(),
                    link_target: "~/.agents/skills/code-review".into(),
                },
                Action::AppendBlock {
                    path: "AGENTS.md".into(),
                    marker: "session=loop-42-reviewer".into(),
                    content:
                        "<!-- agent-profile:begin session=loop-42-reviewer role=reviewer -->\n"
                            .into(),
                },
            ],
            skipped: vec![Skipped {
                field: "skills".into(),
                reason: "cannot express".into(),
                hint: None,
            }],
            notes: vec![],
        }
    }

    #[test]
    fn plan_round_trips_through_json_contract() {
        let _ = Synthetic; // the trait object shape compiles
        let plan = synthetic_plan();
        let json = serde_json::to_value(&plan).unwrap();
        // Contract field spellings from design §2/§3.4.
        assert_eq!(json["actions"][0]["op"], "create");
        assert_eq!(json["actions"][1]["op"], "merge-keys");
        assert_eq!(json["actions"][1]["keys"][0], "mcp_servers.github");
        assert_eq!(json["actions"][2]["op"], "symlink");
        assert_eq!(
            json["actions"][2]["linkTarget"],
            "~/.agents/skills/code-review"
        );
        assert_eq!(json["actions"][3]["op"], "append-block");
        assert_eq!(json["actions"][3]["marker"], "session=loop-42-reviewer");
        let back: Plan = serde_json::from_value(json).unwrap();
        assert_eq!(back, plan);
    }

    #[test]
    fn plan_context_resolves_display_paths() {
        let ctx = PlanContext {
            scope: Scope::Repo,
            repo_root: PathBuf::from("/repo"),
            workspace_root: PathBuf::from("/repo/.agent-profile"),
            home: PathBuf::from("/home/u"),
            session_id: None,
        };
        assert_eq!(
            ctx.resolve("~/.codex/config.toml"),
            PathBuf::from("/home/u/.codex/config.toml")
        );
        assert_eq!(ctx.resolve("AGENTS.md"), PathBuf::from("/repo/AGENTS.md"));
    }

    #[test]
    fn append_block_is_idempotent_by_marker() {
        let action = Action::AppendBlock {
            path: "AGENTS.md".into(),
            marker: "role=qa".into(),
            content:
                "<!-- agent-profile:begin role=qa -->\n@x.md\n<!-- agent-profile:end role=qa -->\n"
                    .into(),
        };
        let appended = desired_file_state(&action, Some("# Existing\n")).unwrap();
        assert!(appended.starts_with("# Existing\n<!-- agent-profile:begin role=qa -->"));
        // Re-running against the appended state changes nothing.
        let again = desired_file_state(&action, Some(&appended)).unwrap();
        assert_eq!(again, appended);
    }
}
